# Generated by Django 3.2.9 on 2021-12-04 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='teams',
            new_name='team',
        ),
    ]
